-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = 'tokyonight'

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, '@annotation', { link = 'PreProc' })
hi(0, '@attribute', { link = 'PreProc' })
hi(0, '@character.printf', { link = 'SpecialChar' })
hi(0, '@character.special', { link = 'SpecialChar' })
hi(0, '@comment.error', { fg = '#db4b4b' })
hi(0, '@comment.hint', { fg = '#1abc9c' })
hi(0, '@comment.info', { fg = '#0db9d7' })
hi(0, '@comment.note', { fg = '#1abc9c' })
hi(0, '@comment.todo', { fg = '#7aa2f7' })
hi(0, '@comment.warning', { fg = '#e0af68' })
hi(0, '@constant.builtin', { link = 'Special' })
hi(0, '@constant.macro', { link = 'Define' })
hi(0, '@constructor', { fg = '#bb9af7' })
hi(0, '@constructor.tsx', { fg = '#2ac3de' })
hi(0, '@diff.delta', { link = 'DiffChange' })
hi(0, '@diff.minus', { link = 'DiffDelete' })
hi(0, '@diff.plus', { link = 'DiffAdd' })
hi(0, '@function.builtin', { link = 'Special' })
hi(0, '@function.call', { link = '@function' })
hi(0, '@function.macro', { link = 'Macro' })
hi(0, '@function.method', { link = 'Function' })
hi(0, '@function.method.call', { link = '@function.method' })
hi(0, '@ibl.indent.char.1', { fg = '#627e97', nocombine = true })
hi(0, '@ibl.scope.char.1', { fg = '#2ac3de', nocombine = true })
hi(0, '@ibl.scope.underline.1', { sp = '#2ac3de', underline = true })
hi(0, '@ibl.whitespace.char.1', { fg = '#627e97', nocombine = true })
hi(0, '@keyword', { fg = '#9d7cd8' })
hi(0, '@keyword.conditional', { link = 'Conditional' })
hi(0, '@keyword.coroutine', { link = '@keyword' })
hi(0, '@keyword.debug', { link = 'Debug' })
hi(0, '@keyword.directive', { link = 'PreProc' })
hi(0, '@keyword.directive.define', { link = 'Define' })
hi(0, '@keyword.exception', { link = 'Exception' })
hi(0, '@keyword.function', { fg = '#bb9af7' })
hi(0, '@keyword.import', { link = 'Include' })
hi(0, '@keyword.operator', { link = '@operator' })
hi(0, '@keyword.repeat', { link = 'Repeat' })
hi(0, '@keyword.return', { link = '@keyword' })
hi(0, '@keyword.storage', { link = 'StorageClass' })
hi(0, '@label', { fg = '#7aa2f7' })
hi(0, '@lsp.type.boolean', { link = '@boolean' })
hi(0, '@lsp.type.builtinType', { link = '@type.builtin' })
hi(0, '@lsp.type.comment', { link = '@comment' })
hi(0, '@lsp.type.decorator', { link = '@attribute' })
hi(0, '@lsp.type.deriveHelper', { link = '@attribute' })
hi(0, '@lsp.type.enum', { link = '@type' })
hi(0, '@lsp.type.enumMember', { link = '@constant' })
hi(0, '@lsp.type.escapeSequence', { link = '@string.escape' })
hi(0, '@lsp.type.formatSpecifier', { link = '@markup.list' })
hi(0, '@lsp.type.generic', { link = '@variable' })
hi(0, '@lsp.type.interface', { fg = '#57c5e5' })
hi(0, '@lsp.type.keyword', { link = '@keyword' })
hi(0, '@lsp.type.lifetime', { link = '@keyword.storage' })
hi(0, '@lsp.type.namespace', { link = '@module' })
hi(0, '@lsp.type.namespace.python', { link = '@variable' })
hi(0, '@lsp.type.number', { link = '@number' })
hi(0, '@lsp.type.operator', { link = '@operator' })
hi(0, '@lsp.type.parameter', { link = '@variable.parameter' })
hi(0, '@lsp.type.property', { link = '@property' })
hi(0, '@lsp.type.selfKeyword', { link = '@variable.builtin' })
hi(0, '@lsp.type.selfTypeKeyword', { link = '@variable.builtin' })
hi(0, '@lsp.type.string', { link = '@string' })
hi(0, '@lsp.type.typeAlias', { link = '@type.definition' })
hi(0, '@lsp.type.unresolvedReference', { sp = '#db4b4b', undercurl = true })
hi(0, '@lsp.type.variable', {})
hi(0, '@lsp.typemod.class.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.enum.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.enumMember.defaultLibrary', { link = '@constant.builtin' })
hi(0, '@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.keyword.async', { link = '@keyword.coroutine' })
hi(0, '@lsp.typemod.keyword.injected', { link = '@keyword' })
hi(0, '@lsp.typemod.macro.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.operator.injected', { link = '@operator' })
hi(0, '@lsp.typemod.string.injected', { link = '@string' })
hi(0, '@lsp.typemod.struct.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.type.defaultLibrary', { fg = '#27a1b9' })
hi(0, '@lsp.typemod.typeAlias.defaultLibrary', { fg = '#27a1b9' })
hi(0, '@lsp.typemod.variable.callable', { link = '@function' })
hi(0, '@lsp.typemod.variable.defaultLibrary', { link = '@variable.builtin' })
hi(0, '@lsp.typemod.variable.injected', { link = '@variable' })
hi(0, '@lsp.typemod.variable.static', { link = '@constant' })
hi(0, '@markup', { link = '@none' })
hi(0, '@markup.emphasis', { italic = true })
hi(0, '@markup.environment', { link = 'Macro' })
hi(0, '@markup.environment.name', { link = 'Type' })
hi(0, '@markup.heading', { link = 'Title' })
hi(0, '@markup.heading.1.delimiter.vimdoc', { bg = '#011628', fg = '#011628', nocombine = true, sp = '#cbe0f0', underdouble = true })
hi(0, '@markup.heading.1.markdown', { bg = '#24293b', bold = true, fg = '#7aa2f7' })
hi(0, '@markup.heading.2.delimiter.vimdoc', { bg = '#011628', fg = '#011628', nocombine = true, sp = '#cbe0f0', underline = true })
hi(0, '@markup.heading.2.markdown', { bg = '#2e2a2d', bold = true, fg = '#e0af68' })
hi(0, '@markup.heading.3.markdown', { bg = '#272d2d', bold = true, fg = '#9ece6a' })
hi(0, '@markup.heading.4.markdown', { bg = '#1a2b32', bold = true, fg = '#1abc9c' })
hi(0, '@markup.heading.5.markdown', { bg = '#2a283b', bold = true, fg = '#bb9af7' })
hi(0, '@markup.heading.6.markdown', { bg = '#272538', bold = true, fg = '#9d7cd8' })
hi(0, '@markup.heading.7.markdown', { bg = '#31282c', bold = true, fg = '#ff9e64' })
hi(0, '@markup.heading.8.markdown', { bg = '#302430', bold = true, fg = '#f7768e' })
hi(0, '@markup.link', { fg = '#1abc9c' })
hi(0, '@markup.link.label', { link = 'SpecialChar' })
hi(0, '@markup.link.label.symbol', { link = 'Identifier' })
hi(0, '@markup.link.url', { link = 'Underlined' })
hi(0, '@markup.list', { fg = '#89ddff' })
hi(0, '@markup.list.checked', { fg = '#73daca' })
hi(0, '@markup.list.markdown', { bold = true, fg = '#ff9e64' })
hi(0, '@markup.list.unchecked', { fg = '#7aa2f7' })
hi(0, '@markup.math', { link = 'Special' })
hi(0, '@markup.raw', { link = 'String' })
hi(0, '@markup.raw.markdown_inline', { bg = '#414868', fg = '#7aa2f7' })
hi(0, '@module', { link = 'Include' })
hi(0, '@module.builtin', { fg = '#f7768e' })
hi(0, '@namespace.builtin', { link = '@variable.builtin' })
hi(0, '@number.float', { link = 'Float' })
hi(0, '@operator', { fg = '#89ddff' })
hi(0, '@property', { fg = '#73daca' })
hi(0, '@punctuation.bracket', { fg = '#b4d0e9' })
hi(0, '@punctuation.delimiter', { fg = '#89ddff' })
hi(0, '@punctuation.special', { fg = '#89ddff' })
hi(0, '@punctuation.special.markdown', { fg = '#ff9e64' })
hi(0, '@string.documentation', { fg = '#e0af68' })
hi(0, '@string.escape', { fg = '#bb9af7' })
hi(0, '@string.regexp', { fg = '#b4f9f8' })
hi(0, '@tag', { link = 'Label' })
hi(0, '@tag.attribute', { link = '@property' })
hi(0, '@tag.delimiter', { link = 'Delimiter' })
hi(0, '@tag.delimiter.tsx', { fg = '#5d7ab8' })
hi(0, '@tag.javascript', { fg = '#f7768e' })
hi(0, '@tag.tsx', { fg = '#f7768e' })
hi(0, '@type.builtin', { fg = '#27a1b9' })
hi(0, '@type.definition', { link = 'Typedef' })
hi(0, '@type.qualifier', { link = '@keyword' })
hi(0, '@variable', { fg = '#cbe0f0' })
hi(0, '@variable.builtin', { fg = '#f7768e' })
hi(0, '@variable.member', { fg = '#73daca' })
hi(0, '@variable.parameter', { fg = '#e0af68' })
hi(0, '@variable.parameter.builtin', { fg = '#dab484' })
hi(0, 'BlinkCmpDoc', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'BlinkCmpDocBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'BlinkCmpGhostText', { fg = '#414868' })
hi(0, 'BlinkCmpKindArray', { link = 'LspKindArray' })
hi(0, 'BlinkCmpKindBoolean', { link = 'LspKindBoolean' })
hi(0, 'BlinkCmpKindClass', { link = 'LspKindClass' })
hi(0, 'BlinkCmpKindCodeium', { fg = '#1abc9c' })
hi(0, 'BlinkCmpKindColor', { link = 'LspKindColor' })
hi(0, 'BlinkCmpKindConstant', { link = 'LspKindConstant' })
hi(0, 'BlinkCmpKindConstructor', { link = 'LspKindConstructor' })
hi(0, 'BlinkCmpKindCopilot', { fg = '#1abc9c' })
hi(0, 'BlinkCmpKindDefault', { fg = '#b4d0e9' })
hi(0, 'BlinkCmpKindEnum', { link = 'LspKindEnum' })
hi(0, 'BlinkCmpKindEnumMember', { link = 'LspKindEnumMember' })
hi(0, 'BlinkCmpKindEvent', { link = 'LspKindEvent' })
hi(0, 'BlinkCmpKindField', { link = 'LspKindField' })
hi(0, 'BlinkCmpKindFile', { link = 'LspKindFile' })
hi(0, 'BlinkCmpKindFolder', { link = 'LspKindFolder' })
hi(0, 'BlinkCmpKindFunction', { link = 'LspKindFunction' })
hi(0, 'BlinkCmpKindInterface', { link = 'LspKindInterface' })
hi(0, 'BlinkCmpKindKey', { link = 'LspKindKey' })
hi(0, 'BlinkCmpKindKeyword', { link = 'LspKindKeyword' })
hi(0, 'BlinkCmpKindMethod', { link = 'LspKindMethod' })
hi(0, 'BlinkCmpKindModule', { link = 'LspKindModule' })
hi(0, 'BlinkCmpKindNamespace', { link = 'LspKindNamespace' })
hi(0, 'BlinkCmpKindNull', { link = 'LspKindNull' })
hi(0, 'BlinkCmpKindNumber', { link = 'LspKindNumber' })
hi(0, 'BlinkCmpKindObject', { link = 'LspKindObject' })
hi(0, 'BlinkCmpKindOperator', { link = 'LspKindOperator' })
hi(0, 'BlinkCmpKindPackage', { link = 'LspKindPackage' })
hi(0, 'BlinkCmpKindProperty', { link = 'LspKindProperty' })
hi(0, 'BlinkCmpKindReference', { link = 'LspKindReference' })
hi(0, 'BlinkCmpKindSnippet', { link = 'LspKindSnippet' })
hi(0, 'BlinkCmpKindString', { link = 'LspKindString' })
hi(0, 'BlinkCmpKindStruct', { link = 'LspKindStruct' })
hi(0, 'BlinkCmpKindSupermaven', { fg = '#1abc9c' })
hi(0, 'BlinkCmpKindTabNine', { fg = '#1abc9c' })
hi(0, 'BlinkCmpKindText', { link = 'LspKindText' })
hi(0, 'BlinkCmpKindTypeParameter', { link = 'LspKindTypeParameter' })
hi(0, 'BlinkCmpKindUnit', { link = 'LspKindUnit' })
hi(0, 'BlinkCmpKindValue', { link = 'LspKindValue' })
hi(0, 'BlinkCmpKindVariable', { link = 'LspKindVariable' })
hi(0, 'BlinkCmpLabel', { fg = '#cbe0f0' })
hi(0, 'BlinkCmpLabelDeprecated', { fg = '#627e97', strikethrough = true })
hi(0, 'BlinkCmpLabelMatch', { fg = '#2ac3de' })
hi(0, 'BlinkCmpMenu', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'BlinkCmpMenuBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'BlinkCmpSignatureHelp', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'BlinkCmpSignatureHelpBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'Bold', { bold = true, fg = '#cbe0f0' })
hi(0, 'Character', { fg = '#9ece6a' })
hi(0, 'ColorColumn', { bg = '#143652' })
hi(0, 'Comment', { fg = '#565f89' })
hi(0, 'ComplHint', { fg = '#414868' })
hi(0, 'Conceal', { fg = '#737aa2' })
hi(0, 'Constant', { fg = '#ff9e64' })
hi(0, 'CurSearch', { link = 'IncSearch' })
hi(0, 'Cursor', { bg = '#cbe0f0', fg = '#011628' })
hi(0, 'CursorColumn', { bg = '#143652' })
hi(0, 'CursorIM', { bg = '#cbe0f0', fg = '#011628' })
hi(0, 'CursorLine', { bg = '#143652' })
hi(0, 'CursorLineNr', { bold = true, fg = '#ff9e64' })
hi(0, 'DapStoppedLine', { bg = '#2e2a2d' })
hi(0, 'Debug', { fg = '#ff9e64' })
hi(0, 'Delimiter', { link = 'Special' })
hi(0, 'DiagnosticError', { fg = '#db4b4b' })
hi(0, 'DiagnosticHint', { fg = '#1abc9c' })
hi(0, 'DiagnosticInfo', { fg = '#0db9d7' })
hi(0, 'DiagnosticUnderlineError', { sp = '#db4b4b', undercurl = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#1abc9c', undercurl = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#0db9d7', undercurl = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#e0af68', undercurl = true })
hi(0, 'DiagnosticUnnecessary', { fg = '#414868' })
hi(0, 'DiagnosticVirtualTextError', { bg = '#2d202a', fg = '#db4b4b' })
hi(0, 'DiagnosticVirtualTextHint', { bg = '#1a2b32', fg = '#1abc9c' })
hi(0, 'DiagnosticVirtualTextInfo', { bg = '#192b38', fg = '#0db9d7' })
hi(0, 'DiagnosticVirtualTextWarn', { bg = '#2e2a2d', fg = '#e0af68' })
hi(0, 'DiagnosticWarn', { fg = '#e0af68' })
hi(0, 'DiffAdd', { bg = '#243e4a' })
hi(0, 'DiffChange', { bg = '#1f2231' })
hi(0, 'DiffDelete', { bg = '#4a272f' })
hi(0, 'DiffText', { bg = '#394b70' })
hi(0, 'Directory', { fg = '#7aa2f7' })
hi(0, 'EndOfBuffer', { fg = '#011628' })
hi(0, 'Error', { fg = '#db4b4b' })
hi(0, 'ErrorMsg', { fg = '#db4b4b' })
hi(0, 'FloatBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'FloatTitle', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'FoldColumn', { bg = '#011628', fg = '#565f89' })
hi(0, 'Folded', { bg = '#627e97', fg = '#7aa2f7' })
hi(0, 'Foo', { bg = '#ff007c', fg = '#cbe0f0' })
hi(0, 'Function', { fg = '#7aa2f7' })
hi(0, 'GitSignsAdd', { fg = '#449dab' })
hi(0, 'GitSignsChange', { fg = '#6183bb' })
hi(0, 'GitSignsDelete', { fg = '#914c54' })
hi(0, 'GitSignsStagedAdd', { fg = '#224e55' })
hi(0, 'GitSignsStagedAddCul', { fg = '#224e55' })
hi(0, 'GitSignsStagedAddLn', { bg = '#243e4a' })
hi(0, 'GitSignsStagedAddNr', { fg = '#224e55' })
hi(0, 'GitSignsStagedChange', { fg = '#30415d' })
hi(0, 'GitSignsStagedChangeCul', { fg = '#30415d' })
hi(0, 'GitSignsStagedChangeLn', { bg = '#1f2231' })
hi(0, 'GitSignsStagedChangeNr', { fg = '#30415d' })
hi(0, 'GitSignsStagedChangedelete', { fg = '#30415d' })
hi(0, 'GitSignsStagedChangedeleteCul', { fg = '#30415d' })
hi(0, 'GitSignsStagedChangedeleteLn', { bg = '#1f2231' })
hi(0, 'GitSignsStagedChangedeleteNr', { fg = '#30415d' })
hi(0, 'GitSignsStagedDelete', { fg = '#48262a' })
hi(0, 'GitSignsStagedDeleteCul', { fg = '#48262a' })
hi(0, 'GitSignsStagedDeleteNr', { fg = '#48262a' })
hi(0, 'GitSignsStagedTopdelete', { fg = '#48262a' })
hi(0, 'GitSignsStagedTopdeleteCul', { fg = '#48262a' })
hi(0, 'GitSignsStagedTopdeleteNr', { fg = '#48262a' })
hi(0, 'GitSignsStagedUntracked', { fg = '#224e55' })
hi(0, 'GitSignsStagedUntrackedCul', { fg = '#224e55' })
hi(0, 'GitSignsStagedUntrackedLn', { bg = '#243e4a' })
hi(0, 'GitSignsStagedUntrackedNr', { fg = '#224e55' })
hi(0, 'IblIndent', { fg = '#627e97', nocombine = true })
hi(0, 'IblScope', { fg = '#2ac3de', nocombine = true })
hi(0, 'IblWhitespace', { fg = '#627e97' })
hi(0, 'Identifier', { fg = '#bb9af7' })
hi(0, 'IncSearch', { bg = '#ff9e64', fg = '#15161e' })
hi(0, 'IndentBlanklineChar', { fg = '#627e97', nocombine = true })
hi(0, 'IndentBlanklineContextChar', { fg = '#2ac3de', nocombine = true })
hi(0, 'Italic', { fg = '#cbe0f0', italic = true })
hi(0, 'Keyword', { fg = '#7dcfff' })
hi(0, 'LazyProgressDone', { bold = true, fg = '#ff007c' })
hi(0, 'LazyProgressTodo', { bold = true, fg = '#627e97' })
hi(0, 'LineNr', { fg = '#627e97' })
hi(0, 'LineNrAbove', { fg = '#627e97' })
hi(0, 'LineNrBelow', { fg = '#627e97' })
hi(0, 'LspCodeLens', { fg = '#565f89' })
hi(0, 'LspInfoBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'LspInlayHint', { bg = '#1d202d', fg = '#545c7e' })
hi(0, 'LspKindArray', { link = '@punctuation.bracket' })
hi(0, 'LspKindBoolean', { link = '@boolean' })
hi(0, 'LspKindClass', { link = '@type' })
hi(0, 'LspKindColor', { link = 'Special' })
hi(0, 'LspKindConstant', { link = '@constant' })
hi(0, 'LspKindConstructor', { link = '@constructor' })
hi(0, 'LspKindEnum', { link = '@lsp.type.enum' })
hi(0, 'LspKindEnumMember', { link = '@lsp.type.enumMember' })
hi(0, 'LspKindEvent', { link = 'Special' })
hi(0, 'LspKindField', { link = '@variable.member' })
hi(0, 'LspKindFile', { link = 'Normal' })
hi(0, 'LspKindFolder', { link = 'Directory' })
hi(0, 'LspKindFunction', { link = '@function' })
hi(0, 'LspKindInterface', { link = '@lsp.type.interface' })
hi(0, 'LspKindKey', { link = '@variable.member' })
hi(0, 'LspKindKeyword', { link = '@lsp.type.keyword' })
hi(0, 'LspKindMethod', { link = '@function.method' })
hi(0, 'LspKindModule', { link = '@module' })
hi(0, 'LspKindNamespace', { link = '@module' })
hi(0, 'LspKindNull', { link = '@constant.builtin' })
hi(0, 'LspKindNumber', { link = '@number' })
hi(0, 'LspKindObject', { link = '@constant' })
hi(0, 'LspKindOperator', { link = '@operator' })
hi(0, 'LspKindPackage', { link = '@module' })
hi(0, 'LspKindProperty', { link = '@property' })
hi(0, 'LspKindReference', { link = '@markup.link' })
hi(0, 'LspKindSnippet', { link = 'Conceal' })
hi(0, 'LspKindString', { link = '@string' })
hi(0, 'LspKindStruct', { link = '@lsp.type.struct' })
hi(0, 'LspKindText', { link = '@markup' })
hi(0, 'LspKindTypeParameter', { link = '@lsp.type.typeParameter' })
hi(0, 'LspKindUnit', { link = '@lsp.type.struct' })
hi(0, 'LspKindValue', { link = '@string' })
hi(0, 'LspKindVariable', { link = '@variable' })
hi(0, 'LspReferenceRead', { bg = '#627e97' })
hi(0, 'LspReferenceText', { bg = '#627e97' })
hi(0, 'LspReferenceWrite', { bg = '#627e97' })
hi(0, 'LspSignatureActiveParameter', { bg = '#1f3147', bold = true })
hi(0, 'MatchParen', { bold = true, fg = '#ff9e64' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi(0, 'MiniClueBorder', { link = 'FloatBorder' })
hi(0, 'MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniClueDescSingle', { link = 'NormalFloat' })
hi(0, 'MiniClueNextKey', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
hi(0, 'MiniClueSeparator', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniClueTitle', { link = 'FloatTitle' })
hi(0, 'MiniCompletionActiveParameter', { underline = true })
hi(0, 'MiniCursorword', { bg = '#627e97' })
hi(0, 'MiniCursorwordCurrent', { bg = '#627e97' })
hi(0, 'MiniDepsChangeAdded', { link = 'diffAdded' })
hi(0, 'MiniDepsChangeRemoved', { link = 'diffRemoved' })
hi(0, 'MiniDepsHint', { link = 'DiagnosticHint' })
hi(0, 'MiniDepsInfo', { link = 'DiagnosticInfo' })
hi(0, 'MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi(0, 'MiniDepsPlaceholder', { link = 'Comment' })
hi(0, 'MiniDepsTitle', { link = 'Title' })
hi(0, 'MiniDepsTitleError', { bg = '#914c54', fg = '#15161e' })
hi(0, 'MiniDepsTitleSame', { link = 'Comment' })
hi(0, 'MiniDepsTitleUpdate', { bg = '#449dab', fg = '#15161e' })
hi(0, 'MiniDiffOverAdd', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverChange', { link = 'DiffText' })
hi(0, 'MiniDiffOverContext', { link = 'DiffChange' })
hi(0, 'MiniDiffOverDelete', { link = 'DiffDelete' })
hi(0, 'MiniDiffSignAdd', { fg = '#449dab' })
hi(0, 'MiniDiffSignChange', { fg = '#6183bb' })
hi(0, 'MiniDiffSignDelete', { fg = '#914c54' })
hi(0, 'MiniFilesFile', { fg = '#cbe0f0' })
hi(0, 'MiniFilesTitleFocused', { bg = '#011423', bold = true, fg = '#27a1b9' })
hi(0, 'MiniHipatternsFixme', { bg = '#db4b4b', bold = true, fg = '#15161e' })
hi(0, 'MiniHipatternsHack', { bg = '#e0af68', bold = true, fg = '#15161e' })
hi(0, 'MiniHipatternsNote', { bg = '#1abc9c', bold = true, fg = '#15161e' })
hi(0, 'MiniHipatternsTodo', { bg = '#0db9d7', bold = true, fg = '#15161e' })
hi(0, 'MiniIconsAzure', { fg = '#0db9d7' })
hi(0, 'MiniIconsBlue', { fg = '#7aa2f7' })
hi(0, 'MiniIconsCyan', { fg = '#1abc9c' })
hi(0, 'MiniIconsGreen', { fg = '#9ece6a' })
hi(0, 'MiniIconsGrey', { fg = '#cbe0f0' })
hi(0, 'MiniIconsOrange', { fg = '#ff9e64' })
hi(0, 'MiniIconsPurple', { fg = '#9d7cd8' })
hi(0, 'MiniIconsRed', { fg = '#f7768e' })
hi(0, 'MiniIconsYellow', { fg = '#e0af68' })
hi(0, 'MiniIndentscopePrefix', { nocombine = true })
hi(0, 'MiniIndentscopeSymbol', { fg = '#2ac3de', nocombine = true })
hi(0, 'MiniJump', { bg = '#ff007c', fg = '#ffffff' })
hi(0, 'MiniJump2dDim', { link = 'Comment' })
hi(0, 'MiniJump2dSpot', { bold = true, fg = '#ff007c', nocombine = true })
hi(0, 'MiniJump2dSpotAhead', { bg = '#011423', fg = '#1abc9c', nocombine = true })
hi(0, 'MiniJump2dSpotUnique', { bold = true, fg = '#ff9e64', nocombine = true })
hi(0, 'MiniMapNormal', { link = 'NormalFloat' })
hi(0, 'MiniMapSymbolCount', { link = 'Special' })
hi(0, 'MiniMapSymbolLine', { link = 'Title' })
hi(0, 'MiniMapSymbolView', { link = 'Delimiter' })
hi(0, 'MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi(0, 'MiniPickBorder', { link = 'FloatBorder' })
hi(0, 'MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniPickBorderText', { bg = '#011423', fg = '#1abc9c' })
hi(0, 'MiniPickHeader', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickIconDirectory', { link = 'Directory' })
hi(0, 'MiniPickIconFile', { link = 'MiniPickNormal' })
hi(0, 'MiniPickMatchCurrent', { link = 'CursorLine' })
hi(0, 'MiniPickMatchMarked', { link = 'Visual' })
hi(0, 'MiniPickMatchRanges', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickNormal', { link = 'NormalFloat' })
hi(0, 'MiniPickPreviewLine', { link = 'CursorLine' })
hi(0, 'MiniPickPreviewRegion', { link = 'IncSearch' })
hi(0, 'MiniPickPrompt', { bg = '#011423', fg = '#0db9d7' })
hi(0, 'MiniStarterCurrent', { nocombine = true })
hi(0, 'MiniStarterFooter', { fg = '#e0af68', italic = true })
hi(0, 'MiniStarterHeader', { fg = '#7aa2f7' })
hi(0, 'MiniStarterInactive', { fg = '#565f89' })
hi(0, 'MiniStarterItem', { bg = '#011628', fg = '#cbe0f0' })
hi(0, 'MiniStarterItemBullet', { fg = '#27a1b9' })
hi(0, 'MiniStarterItemPrefix', { fg = '#e0af68' })
hi(0, 'MiniStarterQuery', { fg = '#0db9d7' })
hi(0, 'MiniStarterSection', { fg = '#2ac3de' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#627e97', fg = '#b4d0e9' })
hi(0, 'MiniStatuslineFileinfo', { bg = '#627e97', fg = '#b4d0e9' })
hi(0, 'MiniStatuslineFilename', { bg = '#143652', fg = '#b4d0e9' })
hi(0, 'MiniStatuslineInactive', { bg = '#011423', fg = '#7aa2f7' })
hi(0, 'MiniStatuslineModeCommand', { bg = '#e0af68', bold = true, fg = '#15161e' })
hi(0, 'MiniStatuslineModeInsert', { bg = '#9ece6a', bold = true, fg = '#15161e' })
hi(0, 'MiniStatuslineModeNormal', { bg = '#7aa2f7', bold = true, fg = '#15161e' })
hi(0, 'MiniStatuslineModeOther', { bg = '#1abc9c', bold = true, fg = '#15161e' })
hi(0, 'MiniStatuslineModeReplace', { bg = '#f7768e', bold = true, fg = '#15161e' })
hi(0, 'MiniStatuslineModeVisual', { bg = '#bb9af7', bold = true, fg = '#15161e' })
hi(0, 'MiniSurround', { bg = '#ff9e64', fg = '#15161e' })
hi(0, 'MiniTablineCurrent', { bg = '#011423', fg = '#b4d0e9', bold = true, sp = '#f7768e', underline = true })
hi(0, 'MiniTablineFill', { bg = '#011423' })
hi(0, 'MiniTablineHidden', { bg = '#15161e', fg = '#737aa2' })
hi(0, 'MiniTablineModifiedCurrent', { bg = '#627e97', fg = '#e0af68' })
hi(0, 'MiniTablineModifiedHidden', { bg = '#011423', fg = '#a58354' })
hi(0, 'MiniTablineModifiedVisible', { bg = '#011423', fg = '#e0af68' })
hi(0, 'MiniTablineTabpagesection', { bg = '#627e97' })
hi(0, 'MiniTablineVisible', {})
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#f7768e' })
hi(0, 'MiniTestPass', { bold = true, fg = '#9ece6a' })
hi(0, 'MiniTrailspace', { bg = '#f7768e' })
hi(0, 'ModeMsg', { bold = true, fg = '#b4d0e9' })
hi(0, 'MoreMsg', { fg = '#7aa2f7' })
hi(0, 'MsgArea', { fg = '#b4d0e9' })
hi(0, 'NeoTreeDimText', { fg = '#627e97' })
hi(0, 'NeoTreeDotfile', { fg = '#626262' })
hi(0, 'NeoTreeFadeText1', { fg = '#626262' })
hi(0, 'NeoTreeFadeText2', { fg = '#444444' })
hi(0, 'NeoTreeFileName', { fg = '#b4d0e9' })
hi(0, 'NeoTreeFileNameOpened', { bold = true })
hi(0, 'NeoTreeFileStats', { fg = '#485f72' })
hi(0, 'NeoTreeFileStatsHeader', { bold = true, fg = '#667b8c', italic = true })
hi(0, 'NeoTreeFloatTitle', { bg = '#011423', fg = '#b4d0e9' })
hi(0, 'NeoTreeGitConflict', { bold = true, fg = '#ff8700', italic = true })
hi(0, 'NeoTreeGitModified', { fg = '#ff9e64' })
hi(0, 'NeoTreeGitStaged', { fg = '#73daca' })
hi(0, 'NeoTreeGitUnstaged', { link = 'NeoTreeGitConflict' })
hi(0, 'NeoTreeGitUntracked', { fg = '#bb9af7' })
hi(0, 'NeoTreeMessage', { fg = '#364c5e', italic = true })
hi(0, 'NeoTreeModified', { fg = '#d7d787' })
hi(0, 'NeoTreeNormal', { bg = '#011423', fg = '#b4d0e9' })
hi(0, 'NeoTreeNormalNC', { bg = '#011423', fg = '#b4d0e9' })
hi(0, 'NeoTreeRootName', { bold = true, italic = true })
hi(0, 'NeoTreeTabActive', { bg = '#011423', bold = true, fg = '#7aa2f7' })
hi(0, 'NeoTreeTabInactive', { bg = '#01101c', fg = '#545c7e' })
hi(0, 'NeoTreeTabSeparatorActive', { bg = '#011423', fg = '#7aa2f7' })
hi(0, 'NeoTreeTabSeparatorInactive', { bg = '#01101c', fg = '#011628' })
hi(0, 'NeoTreeTitleBar', { bg = '#27a1b9', fg = '#011423' })
hi(0, 'NeogitActiveItem', { bg = '#23a2b8', bold = true, ctermfg = 5, fg = '#011628' })
hi(0, 'NeogitBranch', { fg = '#bb9af7' })
hi(0, 'NeogitBranchHead', { bold = true, ctermfg = 4, fg = '#7dcfff', underline = true })
hi(0, 'NeogitChangeAdded', { bold = true, ctermfg = 2, fg = '#82a957', italic = true })
hi(0, 'NeogitChangeCopied', { bold = true, ctermfg = 6, fg = '#70b5d1', italic = true })
hi(0, 'NeogitChangeDeleted', { bold = true, ctermfg = 1, fg = '#b43e3e', italic = true })
hi(0, 'NeogitChangeModified', { bold = true, ctermfg = 4, fg = '#66aad1', italic = true })
hi(0, 'NeogitChangeNewFile', { bold = true, ctermfg = 2, fg = '#82a957', italic = true })
hi(0, 'NeogitChangeRenamed', { bold = true, ctermfg = 5, fg = '#66aad1', italic = true })
hi(0, 'NeogitChangeUnmerged', { bold = true, ctermfg = 3, fg = '#68acd4', italic = true })
hi(0, 'NeogitChangeUpdated', { bold = true, ctermfg = 3, fg = '#23a2b8', italic = true })
hi(0, 'NeogitCommitViewHeader', { bg = '#70b5d1', ctermfg = 7, fg = '#011628' })
hi(0, 'NeogitDiffAdd', { bg = '#243e4a', ctermfg = 2, fg = '#82a957' })
hi(0, 'NeogitDiffAddCursor', { bg = '#061a2c', ctermfg = 2, fg = '#9ece6a' })
hi(0, 'NeogitDiffAddHighlight', { bg = '#243e4a', fg = '#449dab' })
hi(0, 'NeogitDiffAdditions', { ctermfg = 2, fg = '#82a957' })
hi(0, 'NeogitDiffContext', { bg = '#061a2c' })
hi(0, 'NeogitDiffContextCursor', { bg = '#061a2c' })
hi(0, 'NeogitDiffContextHighlight', { bg = '#3e4d5f', fg = '#b4d0e9' })
hi(0, 'NeogitDiffDelete', { bg = '#4a272f', ctermfg = 1, fg = '#b43e3e' })
hi(0, 'NeogitDiffDeleteCursor', { bg = '#061a2c', ctermfg = 1, fg = '#db4b4b' })
hi(0, 'NeogitDiffDeleteHighlight', { bg = '#4a272f', fg = '#914c54' })
hi(0, 'NeogitDiffDeletions', { ctermfg = 1, fg = '#b43e3e' })
hi(0, 'NeogitDiffHeader', { bg = '#1d3040', bold = true, ctermfg = 3, fg = '#7dcfff' })
hi(0, 'NeogitDiffHeaderHighlight', { bg = '#1d3040', bold = true, ctermfg = 3, fg = '#2ac3de' })
hi(0, 'NeogitFilePath', { ctermfg = 3, fg = '#7dcfff', italic = true })
hi(0, 'NeogitFloatHeader', { bg = '#011628', bold = true, ctermfg = 5 })
hi(0, 'NeogitFloatHeaderHighlight', { bg = '#122536', bold = true, ctermfg = 5, fg = '#89ddff' })
hi(0, 'NeogitGraphAuthor', { ctermfg = 3, fg = '#2ac3de' })
hi(0, 'NeogitGraphBlue', { ctermfg = 4, fg = '#7dcfff' })
hi(0, 'NeogitGraphBoldBlue', { bold = true, ctermfg = 4, fg = '#7dcfff' })
hi(0, 'NeogitGraphBoldCyan', { bold = true, ctermfg = 6, fg = '#89ddff' })
hi(0, 'NeogitGraphBoldGray', { bold = true, ctermfg = 7, fg = '#67737e' })
hi(0, 'NeogitGraphBoldGreen', { bold = true, ctermfg = 2, fg = '#9ece6a' })
hi(0, 'NeogitGraphBoldOrange', { bold = true, ctermfg = 3, fg = '#2ac3de' })
hi(0, 'NeogitGraphBoldPurple', { bold = true, ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitGraphBoldRed', { bold = true, ctermfg = 1, fg = '#db4b4b' })
hi(0, 'NeogitGraphBoldWhite', { bold = true, ctermfg = 7, fg = '#fcfcfc' })
hi(0, 'NeogitGraphBoldYellow', { bold = true, ctermfg = 3, fg = '#7dcfff' })
hi(0, 'NeogitGraphCyan', { ctermfg = 6, fg = '#89ddff' })
hi(0, 'NeogitGraphGray', { ctermfg = 7, fg = '#67737e' })
hi(0, 'NeogitGraphGreen', { ctermfg = 2, fg = '#9ece6a' })
hi(0, 'NeogitGraphOrange', { ctermfg = 3, fg = '#2ac3de' })
hi(0, 'NeogitGraphPurple', { ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitGraphRed', { ctermfg = 1, fg = '#db4b4b' })
hi(0, 'NeogitGraphWhite', { ctermfg = 7, fg = '#fcfcfc' })
hi(0, 'NeogitGraphYellow', { ctermfg = 3, fg = '#7dcfff' })
hi(0, 'NeogitHunkHeader', { bg = '#143652', fg = '#cbe0f0' })
hi(0, 'NeogitHunkHeaderCursor', { bg = '#94d8ff', bold = true, ctermfg = 3, fg = '#011628' })
hi(0, 'NeogitHunkHeaderHighlight', { bg = '#627e97', fg = '#7aa2f7' })
hi(0, 'NeogitHunkMergeHeader', { bg = '#67737e', bold = true, ctermfg = 4, fg = '#122536' })
hi(0, 'NeogitHunkMergeHeaderCursor', { bg = '#70b5d1', bold = true, ctermfg = 4, fg = '#011628' })
hi(0, 'NeogitHunkMergeHeaderHighlight', { bg = '#70b5d1', bold = true, ctermfg = 4, fg = '#011628' })
hi(0, 'NeogitPopupActionKey', { ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitPopupBold', { bold = true })
hi(0, 'NeogitPopupConfigKey', { ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitPopupOptionKey', { ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitPopupSwitchKey', { ctermfg = 5, fg = '#7dcfff' })
hi(0, 'NeogitRemote', { fg = '#9d7cd8' })
hi(0, 'NeogitSectionHeader', { bold = true, ctermfg = 5, fg = '#66aad1' })
hi(0, 'NeogitTagDistance', { ctermfg = 6, fg = '#89ddff' })
hi(0, 'NeogitTagName', { ctermfg = 3, fg = '#7dcfff' })
hi(0, 'NeogitUnmergedInto', { bold = true, ctermfg = 5, fg = '#66aad1' })
hi(0, 'NeogitUnpulledFrom', { bold = true, ctermfg = 5, fg = '#66aad1' })
hi(0, 'NeogitUnpushedTo', { bold = true, ctermfg = 5, fg = '#66aad1' })
hi(0, 'NonText', { fg = '#545c7e' })
hi(0, 'Normal', { bg = '#011628', fg = '#cbe0f0' })
hi(0, 'NormalFloat', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'NormalNC', { bg = '#011628', fg = '#cbe0f0' })
hi(0, 'NormalSB', { bg = '#011423', fg = '#b4d0e9' })
hi(0, 'OCP_275378', { bg = '#275378', fg = '#ffffff' })
hi(0, 'OCP_333333', { bg = '#333333', fg = '#ffffff' })
hi(0, 'OCP_547998', { bg = '#547998', fg = '#ffffff' })
hi(0, 'OCP_627e97', { bg = '#627e97', fg = '#000000' })
hi(0, 'OCP_74705d', { bg = '#74705d', fg = '#ffffff' })
hi(0, 'OCP_777777', { bg = '#777777', fg = '#000000' })
hi(0, 'OCP_aaaaaa', { bg = '#aaaaaa', fg = '#000000' })
hi(0, 'OCP_b4d0e9', { bg = '#b4d0e9', fg = '#000000' })
hi(0, 'OCP_cbe0f0', { bg = '#cbe0f0', fg = '#000000' })
hi(0, 'Operator', { fg = '#89ddff' })
hi(0, 'Pmenu', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'PmenuExtra', { fg = '#9d7cd8' })
hi(0, 'PmenuMatch', { bg = '#011423', fg = '#2ac3de' })
hi(0, 'PmenuMatchSel', { bg = '#546a80', fg = '#2ac3de' })
hi(0, 'PmenuSbar', { bg = '#0b1d2e' })
hi(0, 'PmenuSel', { bg = '#546a80' })
hi(0, 'PmenuThumb', { bg = '#627e97' })
hi(0, 'PreProc', { fg = '#7dcfff' })
hi(0, 'Question', { fg = '#7aa2f7' })
hi(0, 'QuickFixLine', { bg = '#275378', bold = true })
hi(0, 'Search', { bg = '#0a64ac', fg = '#cbe0f0' })
hi(0, 'SignColumn', { bg = '#011628', fg = '#627e97' })
hi(0, 'SignColumnSB', { bg = '#011423', fg = '#627e97' })
hi(0, 'Special', { fg = '#2ac3de' })
hi(0, 'SpecialKey', { fg = '#545c7e' })
hi(0, 'SpellBad', { sp = '#db4b4b', undercurl = true })
hi(0, 'SpellCap', { sp = '#e0af68', undercurl = true })
hi(0, 'SpellLocal', { sp = '#0db9d7', undercurl = true })
hi(0, 'SpellRare', { sp = '#1abc9c', undercurl = true })
hi(0, 'Statement', { fg = '#bb9af7' })
hi(0, 'StatusLine', { bg = '#011423', fg = '#b4d0e9' })
hi(0, 'StatusLineNC', { bg = '#011423', fg = '#627e97' })
hi(0, 'String', { fg = '#9ece6a' })
hi(0, 'Substitute', { bg = '#f7768e', fg = '#15161e' })
hi(0, 'TabLine', { bg = '#011423', fg = '#627e97' })
hi(0, 'TabLineFill', { bg = '#15161e' })
hi(0, 'TabLineSel', { bg = '#7aa2f7', fg = '#15161e' })
hi(0, 'TelescopeBorder', { bg = '#011423', fg = '#27a1b9' })
hi(0, 'TelescopeNormal', { bg = '#011423', fg = '#cbe0f0' })
hi(0, 'TelescopePromptBorder', { bg = '#011423', fg = '#ff9e64' })
hi(0, 'TelescopePromptTitle', { bg = '#011423', fg = '#ff9e64' })
hi(0, 'TelescopeResultsComment', { fg = '#545c7e' })
hi(0, 'Title', { bold = true, fg = '#7aa2f7' })
hi(0, 'Todo', { bg = '#e0af68', fg = '#011628' })
hi(0, 'Type', { fg = '#2ac3de' })
hi(0, 'UfoFoldedBg', { bg = '#627e97' })
hi(0, 'UfoFoldedFg', { fg = '#cbe0f0' })
hi(0, 'VertSplit', { fg = '#547998' })
hi(0, 'Visual', { bg = '#275378' })
hi(0, 'VisualNOS', { bg = '#275378' })
hi(0, 'WarningMsg', { fg = '#e0af68' })
hi(0, 'WhichKey', { fg = '#7dcfff' })
hi(0, 'WhichKeyDesc', { fg = '#bb9af7' })
hi(0, 'WhichKeyGroup', { fg = '#7aa2f7' })
hi(0, 'WhichKeyNormal', { bg = '#011423' })
hi(0, 'WhichKeySeparator', { fg = '#565f89' })
hi(0, 'WhichKeyValue', { fg = '#737aa2' })
hi(0, 'Whitespace', { fg = '#627e97' })
hi(0, 'WildMenu', { bg = '#275378' })
hi(0, 'WinBar', { link = 'StatusLine' })
hi(0, 'WinBarNC', { link = 'StatusLineNC' })
hi(0, 'WinSeparator', { bold = true, fg = '#547998' })
hi(0, 'debugBreakpoint', { bg = '#192b38', fg = '#0db9d7' })
hi(0, 'debugPC', { bg = '#011423' })
hi(0, 'diffAdded', { bg = '#243e4a', fg = '#449dab' })
hi(0, 'diffChanged', { bg = '#1f2231', fg = '#6183bb' })
hi(0, 'diffFile', { fg = '#7aa2f7' })
hi(0, 'diffIndexLine', { fg = '#bb9af7' })
hi(0, 'diffLine', { fg = '#565f89' })
hi(0, 'diffNewFile', { bg = '#243e4a', fg = '#2ac3de' })
hi(0, 'diffOldFile', { bg = '#4a272f', fg = '#2ac3de' })
hi(0, 'diffRemoved', { bg = '#4a272f', fg = '#914c54' })
hi(0, 'dosIniLabel', { link = '@property' })
hi(0, 'healthError', { fg = '#db4b4b' })
hi(0, 'healthSuccess', { fg = '#73daca' })
hi(0, 'healthWarning', { fg = '#e0af68' })
hi(0, 'helpCommand', { bg = '#414868', fg = '#7aa2f7' })
hi(0, 'helpExample', { fg = '#565f89' })
hi(0, 'htmlH1', { bold = true, fg = '#bb9af7' })
hi(0, 'htmlH2', { bold = true, fg = '#7aa2f7' })
hi(0, 'lCursor', { bg = '#cbe0f0', fg = '#011628' })
hi(0, 'qfFileName', { fg = '#7aa2f7' })
hi(0, 'qfLineNr', { fg = '#737aa2' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#15161e'
g.terminal_color_1 = '#f7768e'
g.terminal_color_2 = '#9ece6a'
g.terminal_color_3 = '#e0af68'
g.terminal_color_4 = '#7aa2f7'
g.terminal_color_5 = '#bb9af7'
g.terminal_color_6 = '#7dcfff'
g.terminal_color_7 = '#a9b1d6'
g.terminal_color_8 = '#414868'
g.terminal_color_9 = '#ff899d'
g.terminal_color_10 = '#9fe044'
g.terminal_color_11 = '#faba4a'
g.terminal_color_12 = '#8db0ff'
g.terminal_color_13 = '#c7a9ff'
g.terminal_color_14 = '#a4daff'
g.terminal_color_15 = '#c0caf5'
