cursor #dee2ef
cursor_text_color #c2c6d2

foreground            #dee2ef
background            #0f141c
selection_foreground  #282f4d
selection_background  #bec5eb
url_color             #a7c8ff

color0   #0f141c
color1   #ff729a
color2   #7fff91
color3   #fff872
color4   #8db3f2
color5   #2b4776
color6   #a7c8ff
color7   #eff5ff
color8   #999da5
color9   #ff9fba
color10  #a5ffb2
color11  #fffaa5
color12  #b4d0ff
color13  #c1d8ff
color14  #d7e6ff
color15  #f8fbff
