# font_family                     ComicShannsMono Nerd Font Mono
font_family                       SauceCodePro Nerd Font Mono
bold_font                         auto
italic_font                       auto
bold_italic_font                  auto
font_size                         24
modify_font                       cell_height 110%
undercurl_style                   thin-sparse
cursor_blink_interval             0.5
cursor_stop_blinking_after        5.0
cursor_trail                      1
cursor_trail_decay                0.1 0.4
cursor_trail_start_threshold      2
scrollback_lines                  2000
scrollback_indicator_opacity      1.0
scrollback_pager                  less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
enable_audio_bell                 no
confirm_os_window_close           0
remember_window_size              no
hide_window_decorations           yes
initial_window_width              900
initial_window_height             600
background_blur                   1
background_opacity                0.6
dynamic_background_opacity        yes

# Keybinds
map ctrl+alt+enter                launch --cwd=current
map kitty_mod+t                   new_tab_with_cwd

# Include dank shell themes
include dank-tabs.conf
include dank-theme.conf
